# numpy
numpyはPythonによるあらゆる数値計算を可能にするライブラリです。

多次元配置や行列を簡単に操作できるため、機械学習のみならず、あらゆる分野で活用されています。

In [1]:
import numpy as np

# 基本的な配列の生成
配列の生成には、np.arrayメソッドを使います。

In [2]:
np.array(1)

array(1)

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array([[1, 2], [3, 4], [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

# 形状の確認
配列を操作するようになると、その形状を確認しなければならない状況に多く遭遇します。

その際は、shape属性を参照すると形状を確認できます。

In [5]:
array = np.array([1, 2, 3])
array.shape

(3,)

In [6]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.shape

(3, 2)

# 形状の変換
データ分析の現場では、配列の形状を変換することも多いです。形状の変換には、reshapeメソッドを使います。

特に列ベクトル（列数１の行列）への変換、多次元配列の１次元への変換は必須のテクニックです。

In [7]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
array.reshape(2, 3) #(2, 3)行列へ変換

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
array.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array.ravel()

array([1, 2, 3, 4, 5, 6])

# 選択と抽出
配列の一部を選択・抽出したい場面は多く存在します。

特に：（スライス）の用法についてはきちんと理解しておくべきでしょう。

In [11]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
# １行目を抽出
array[0]

array([1, 2])

In [13]:
# ２行目以降を抽出
array[1:]

array([[3, 4],
       [5, 6]])

In [14]:
# ２行目までを抽出
array[:2]

array([[1, 2],
       [3, 4]])

In [15]:
# １行目の２列目を抽出
array[0, 1]
# array[0][1]

2

## 列ごとの各要素を取り出す機会はかなり多いので、この用法は確実に覚えましょう。

In [16]:
# ２列目を抽出
array[:, 1]

array([2, 4, 6])

# 条件による選択
配列の中から、ある条件を満たす要素のみを取り出したいときや、ある条件を満たす要素を別の値に置き換えたい場合があります。

その際は、whereメソッドなどを使うと便利です。

In [17]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
array > 4

array([[False, False],
       [False, False],
       [ True,  True]])

In [19]:
array[array > 4]

array([5, 6])

ある条件を満たす要素を置き換えるときは、whereメソッドを使うと便利です。

引数の内容は（　条件、　置き換える値、　条件を満たさない要素の値　）です。

In [20]:
X = np.arange(20).reshape(-1, 1)
y = np.random.rand(20)
y = np.where(y < 0.5, 0, 1).reshape(-1, 1)

X[:][y == 1]

array([ 1,  2,  4,  6,  9, 12, 13, 14])

# 配列の結合
複数の配列を結合したいときは、vstackとhstackメソッドを使います。

vstackは縦方向、hstackは横方向にそれぞれ配列を結合します。

In [21]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([[7, 8], [9, 10], [11, 12]])

np.vstack([array_1, array_2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
np.hstack([array_1, array_2])

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

## 形状の異なった配列を同士を連結することはできません。

In [23]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([7, 8, 9, 10, 11, 12])

print(array_1.shape)
print(array_2.shape)

(3, 2)
(6,)


In [24]:
np.stack([array_1, array_2])

ValueError: all input arrays must have the same shape

# 便利な配列生成
## arange
範囲を指定して配列を生成

In [ ]:
np.arange(1, 10)

# zeros 
全ての要素が０である配列を生成

In [25]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# zeros_like
指定した配列と同じ形状のゼロ行列を生成

In [26]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.shape)

(3, 2)


In [27]:
np.zeros_like(array)

array([[0, 0],
       [0, 0],
       [0, 0]])

# ones 
全ての要素が１である配列を生成

In [28]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# ones_like
指定した配列と同じ形状の全ての要素が１である配列を生成

In [29]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array.shape)

(3, 2)


In [30]:
np.ones_like(array)

array([[1, 1],
       [1, 1],
       [1, 1]])

# eye
単位行列を生成

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# linspace
指定した範囲を等間隔で分割した配列を生成

In [33]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 乱数の生成
乱数の生成には、主にrandn, rand, randintのいずれか使います。

- randn: 標準正規分布（平均０，分散１）にしたがって乱数を生成
- rand: ０から１までの範囲で乱数を生成
- randint: 指定した範囲の整数をランダムに抽出

乱数を固定するためには、np.random.seed()を指定します。

In [ ]:
np.random.seed(0)

In [34]:
np.random.randn(10)

array([ 0.50141943, -1.1289379 ,  0.57603414, -0.695446  , -0.74852839,
        0.57856999, -1.04127473,  2.35294454,  2.53509691,  0.4091834 ])

In [35]:
np.random.rand(10)

array([0.42179776, 0.35914595, 0.27556262, 0.66549203, 0.42162867,
       0.93657067, 0.98161163, 0.69001591, 0.90426019, 0.41834261])

In [36]:
np.random.randint(0, 100, 10)

array([25, 58, 49, 84, 78, 10, 38,  3, 10, 22])

# 各種演算
配列に対してもあらゆる演算が可能です。

In [ ]:
array_1 = np.array([[1, 2], [3, 4], [5, 6]])
array_2 = np.array([[7, 8], [9, 10], [11, 12]])

### 四則演算

In [ ]:
array_1 + array_2

In [ ]:
array_1 - array_2

In [ ]:
array_1 * array_2

In [ ]:
array_1 / array_2

### 累乗

In [ ]:
array_1 ** 2

In [ ]:
np.sqrt(array_1)

### 指数関数・対数関数

In [ ]:
np.exp(array)

In [ ]:
np.log1p(array)

# 各種統計量
いろいろな統計量を簡単に計算できます。

In [ ]:
array = np.random.randint(0, 100, 20)
array

### 合計・平均・分散・標準偏差

In [ ]:
np.sum(array)

In [ ]:
np.mean(array)

In [ ]:
np.var(array)

In [ ]:
np.std(array)

### 最大値・最小値

In [37]:
np.max(array)

6

In [38]:
np.argmax(array)

5

In [39]:
np.min(array)

1

In [40]:
np.argmin(array)

0

# その他
その他のよく使う機能をまとめます。

### データ型を確認する

In [41]:
array = np.random.randint(0, 100, 20)
array

array([71,  4,  6, 29, 60, 65, 69, 57, 35, 77,  7, 93, 64, 68, 78, 28, 82,
       56,  7, 86])

In [42]:
array.dtype

dtype('int64')

### データ型を指定して配列を生成する

In [ ]:
array = np.random.randint(0, 100, 20, dtype='int32')
array

In [ ]:
array.dtype

### 桁数を丸める

In [ ]:
array = np.random.randn(10)
array

In [ ]:
np.round(array, 2)