# NumPy お勉強

- NumPy インポート

In [1]:
import numpy as np

## 一次元配列

- array 関数に配列の要素とする, Pythonのリストを渡すことで作成できる

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


- a はNumPyの配列、ndarray object となる

In [5]:
type(a)

numpy.ndarray

- shapeメゾット で一次元、3要素の配列が作成されていることを確認

In [7]:
a.shape

(3,)

## 二次元配列

- array 関数に配列の要素とする、Pythonのリストをネストした二重リストを渡すことで作成できる

In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

- shapeメゾット で 2X3　（2次元、3要素）の行列が作成されていることを確認

In [10]:
b.shape

(2, 3)

## 次元変換

- 次元の変換（変形）を行う

- 6要素の一次元配列を作成

In [15]:
c1 = np.array([0, 1, 2, 3, 4, 5])
c1

array([0, 1, 2, 3, 4, 5])

- reshapeメゾットを使い、二次元の配列（2X3行列）に変換

In [14]:
c2 = c1.reshape((2, 3))
c2

array([[0, 1, 2],
       [3, 4, 5]])

- ravelメゾットを使い、二次元の配列を一次元に変換

In [16]:
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

- ravelメゾットと同様に、flattenメゾットで二次元の配列を一次元に変換

In [17]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

*** ravelは参照・fattenはコピーを返す ***

## データ型

- dtype属性を使いNumPy配列の要素のデータ型を確認できる
- 要素のデータ型は1つにNumPyの型に統一される

- 一次元配列 a の要素のデータ型を確認

In [19]:
a.dtype

dtype('int64')

　 　a　はpythonのint型のデータで作成し、作成時に型宣言をしていないため、自動で*np.int64*が割り当てられます。

- np.int16と型宣言をして配列を作成

In [20]:
d = np.array([1, 2], dtype=np.int16)
d

array([1, 2], dtype=int16)

  　　型情報が付与されている

- dtype属性でデータ型を確認

In [22]:
d.dtype

dtype('int16')

    np.int16のデータ型となっている

- astypeメゾットを使い、np.int16からnp.float16(不動小数点数)に変換

In [24]:
d.astype(np.float16)

array([1., 2.], dtype=float16)

## インデックス・スライス

- 一次元配列

In [25]:
a

array([1, 2, 3])

In [26]:
a[0]

1

In [27]:
a[1:]

array([2, 3])

In [28]:
a[-1]

3

- 二次元配列

In [29]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b[0]

array([1, 2, 3])

In [31]:
b[1, 0]

4

In [32]:
b[:, 2]

array([3, 6])

In [33]:
b[1, :]

array([4, 5, 6])

In [34]:
b[0, 1:]

array([2, 3])

In [35]:
b[:, [0, 2]]

array([[1, 3],
       [4, 6]])

## データ再代入

- 配列の内部データの変更方法